### ISSUE TITLE
Concatenate MBD BSseq December 2015 files

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-olympia.oyster-genomic#14]
@kubu4 could you concatenate files to 18 files corresponding to samples.

For one set just use s4, s5, ~~or~~ s6. (meant to say _and_)

and for a second set use s1-s6. 

thanks

**Comment by kubu4** [comment]
Done. These can be found in Owl/nightingales/O_lurida/20160203_mbdseq/

List of just s6 series concatenated:
zr1394_10_s6.fastq.gz
zr1394_11_s6.fastq.gz
zr1394_12_s6.fastq.gz
zr1394_13_s6.fastq.gz
zr1394_14_s6.fastq.gz
zr1394_15_s6.fastq.gz
zr1394_16_s6.fastq.gz
zr1394_17_s6.fastq.gz
zr1394_18_s6.fastq.gz
zr1394_1_s6.fastq.gz
zr1394_2_s6.fastq.gz
zr1394_3_s6.fastq.gz
zr1394_4_s6.fastq.gz
zr1394_5_s6.fastq.gz
zr1394_6_s6.fastq.gz
zr1394_7_s6.fastq.gz
zr1394_8_s6.fastq.gz
zr1394_9_s6.fastq.gz

List of s1-s6 concatenated:
zr1394_1.fastq.gz
zr1394_10.fastq.gz
zr1394_11.fastq.gz
zr1394_12.fastq.gz
zr1394_13.fastq.gz
zr1394_14.fastq.gz
zr1394_15.fastq.gz
zr1394_16.fastq.gz
zr1394_17.fastq.gz
zr1394_18.fastq.gz
zr1394_2.fastq.gz
zr1394_3.fastq.gz
zr1394_4.fastq.gz
zr1394_5.fastq.gz
zr1394_6.fastq.gz
zr1394_7.fastq.gz
zr1394_8.fastq.gz
zr1394_9.fastq.gz

**Comment by kubu4** [comment]
Ha! As @sr320 just pointed out, there's no reason to "concatenate" just the s6 - there's nothing to concatenate them with!! Duh. :blush: 

However, @sr320 wanted the s4, s5, & s6 concatenated together - which makes much more sense!

Will get this going...

**Comment by kubu4** [comment]
All done (the correct way, this time): 
zr1394_10_s456.fastq.gz
zr1394_11_s456.fastq.gz
zr1394_12_s456.fastq.gz
zr1394_13_s456.fastq.gz
zr1394_14_s456.fastq.gz
zr1394_15_s456.fastq.gz
zr1394_16_s456.fastq.gz
zr1394_17_s456.fastq.gz
zr1394_18_s456.fastq.gz
zr1394_1_s456.fastq.gz
zr1394_2_s456.fastq.gz
zr1394_3_s456.fastq.gz
zr1394_4_s456.fastq.gz
zr1394_5_s456.fastq.gz
zr1394_6_s456.fastq.gz
zr1394_7_s456.fastq.gz
zr1394_8_s456.fastq.gz
zr1394_9_s456.fastq.gz

**Comment by sr320** [comment]
I am pretty sure this did not work..

If you look at the "456" file it is just the same size as the s6 file, thus no concatenating?

same goes for s1-6 concatenated files...

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/20160203_mbdseq_1CBC45B0.png" alt="20160203_mbdseq_1CBC45B0.png"/>

**Comment by kubu4** [comment]
I've fixed the first set. Second set is running. Sorry!!

![_busy__20160411_concatenate_oly_mbdseq](https://cloud.githubusercontent.com/assets/4514104/14444178/e2c0b634-fff8-11e5-84b9-4754e177fd37.jpg)

**Comment by kubu4** [comment]
Aaaaaand, the second group is finished. Again, sorry!

Also, great catch by @sr320! :+1: This is why he's the boss. :sparkles: 

![20160411_concatenate_oly_mbdseq](https://cloud.githubusercontent.com/assets/4514104/14444660/c96816f2-fffb-11e5-9ad6-08731c35971c.jpg)

**Comment by sr320** [comment]
Thanks 🎉
