### ISSUE TITLE
Develop Sampling Protocol for October 5th

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-olympia.oyster-genomic#19]
Currently the plan is for myself and a couple of other folks to sample @ksil91 oysters on October 5th. @kubu4 will not be able to go. 

@ksil91 It would be great if you could add a protocol/procedure to this repo.
thanks

**Comment by ksil91** [comment]
Will do, I'll have a finished protocol up there this weekend!

**Comment by ksil91** [comment]
Here is the link to a Google Doc with instructions: https://docs.google.com/document/d/1900Qel932G-zLeBiqcbPf7CppJnWtRIqdlAckBuiUBQ/edit?usp=sharing

If you'd like me to convert it to markdown and put in the repo somewhere, let me know and let me know what folder it should go under.

Here is a link to the master sheet with the IDs saying which oyster is supposed to be in which population bag, in case an oyster falls out of a bag and you aren't sure what population it belongs to.
https://docs.google.com/spreadsheets/d/1yJEO1I_N_1jE4wC1gcsCPpXNZoHjoIyFluiv-__gRJo/edit?usp=sharing

Please call or email me with any questions before or the day of!

**Comment by sr320** [comment]
Thanks
So Mantle, and Gill go into RNAlater
Muscle into EtoH (85%) 

On the data sheet you have Mantle, Adductor, Gill RNA, Gill EtOH...

**Comment by ksil91** [comment]
Mantle (M), Ctenidia/gills (C), and Adductor Muscle (A) go into 750ul of RNALater. I tried to clarify in the instructions. If the oyster has enough ctenidia to sample 2 "pea-sized" sections, put one sample in RNALater and one sample in EtOH. The EtOH sample is for microbial diversity. Oysters less than 2cm long probably won't have enough ctenidia for both.
