### ISSUE TITLE
O. lurida genome assembly

### ISSUE THREAD

**Issue by ksil91** [RobertsLab/project-olympia.oyster-genomic#21]
I looked through Sam's notebook entries and the summary PDF from BGI, but I just wanted to double check on something before I went ahead with using the new (20160512) genome assembly. What is the difference between the assemblies received 20160314 and 20160512? The assembly receive 20160512 is labelled as the initial small insert library assembly. They say in the PDF they didn't fill in the gaps "due to the length of N50 being shorter than expected". So was the 20150314 assembly made with the larger inserts? Mostly I want to know if I should expect the 20160512 assembly to be missing a significant part of the genome, and therefore if I should expect a significant number of unmapped 2brad/GBS reads. Is there an update on when a genome assembly with gap filling will be done?

**Comment by kubu4** [comment]
It is unknown how the initial scaffolds from 20160314 were constructed.

No update on genome assembly - currently in limbo - may cancel assembly.

**Comment by ksil91** [comment]
Would it be worth looking into other options? We have a Bioinformatics Core that offers project consultation and sometimes has rate assistance for students.

**Comment by sr320** [comment]
Sure it is fine to check with them and see if they have any suggestions. My
goal is to fully assess what we have (and why this week.
thanks

**Comment by sr320** [comment]
It does look like the 20160512 assembly is _only_ the small insert libraries (which seems crazy to me). 

I could not find any documentation on the 20160314 assembly- did they send anything?

**Comment by kubu4** [comment]
They did not send anything other than what's in that folder.

**Comment by ksil91** [comment]
Our Bioinformatics Core will finish the assembly at $95 per "man" hour (not computational time). I can meet with them in person to get a more concrete estimate of cost. I'm also talking to some colleagues here that have assembled their own genomes for advice.

**Comment by sr320** [comment]
Thanks

**Comment by kubu4** [comment]
Putting this info here for posterity.

Met with BGI yesterday ([slides brought by BGI rep](https://github.com/RobertsLab/project-olympia.oyster-genomic/blob/master/docs/20161129_BGI_project_summary_slides.pdf)).

- Terminology clarification: 
  - contigs = paired-end libraries (small insert libraries);
  - scaffolds = contigs + mate-pair libraries (large insert libraries)
- Genome is very large and very complex.
- Can't improve assembly w/o additional sequencing
- Current PacBio (RSII) is too costly
- New PacBio (Sequel) isn't fully tested yet, but will be significantly cheaper than current iteration
- Best option for going forward is to end contract and accept $2500 refund for assembly costs (50% of cost)
- Rep recommended looking into [10x Genomics](https://www.10xgenomics.com/) for additional sequencing

**Comment by ksil91** [comment]
Thanks for the update Sam! Question about the files uploaded 2016-11-30: what is the 639MB "Ostrea_lurida.fa" file, and how does it relate to what they did already with the assembly? Also, just wanted to verify that the Ostrea_lurida.scafSeq from 20160512 is the "best" assembly they were able to produce.

**Comment by kubu4** [comment]
The files you are referring to are in the process of being downloaded and intergrity-checked. I'll let you know more deets when they are ready for use. However, these are the final files we'll be getting from them, so this data set will probably become the go-to data to use for any subsequent analysis/assembly.

Currently, yes, the 20160512 assembly is the best they were able to produce.

**Comment by kubu4** [comment]
Refer to Issue #25 .
