### ISSUE TITLE
QC Reports for 2bRAD libraries KES 1-4?

### ISSUE THREAD

**Issue by ksil91** [RobertsLab/project-olympia.oyster-genomic#24]
I'm resequencing the samples that did not work well the 1st time around, and I wanted to compare the Bioanalyzer QC from the KES 1-4 libraries and my new library.  On the 2bRAD wiki, I only see the Bioanalyzer QC from Sam's library. Do you have the other QC report from Genewiz?

**Comment by kubu4** [comment]
QC report for KES 1-3 were forwarded to you on 12/8/2015. However, you're right. They are NOT on the wiki! Sorry about that! Will get them uploaded later today.

Checking on KES 4...

**Comment by kubu4** [comment]
Found KES 4. Turns out, all of the QC reports were actually in the docs folder in the main repo page; I just never linked to them on the wiki! Doh!

Thanks for catching this @ksil91! 

They are now all linked on the wiki.

Sorry for the hassle and confusion!!
