### ISSUE TITLE
Genome version used for MBD BS mapping?

### ISSUE THREAD

**Issue by ksil91** [RobertsLab/project-olympia.oyster-genomic#25]
I'm going to be starting the 2bRAD genotyping from my new sequencing run, and I wanted to make sure I am using the same genome assembly and same filtering that is being used for the MBD BS mapping.  This is what will be presented on at NSA. As far as I know, there is a [scaffold.fa.fill ](http://owl.fish.washington.edu/O_lurida_genome_assemblies_BGI/20160314/) from 20160314, and [Ostrea_lurida.scafSeq](http://owl.fish.washington.edu/O_lurida_genome_assemblies_BGI/20160512/) from 20160512. Which one are you using, and how did you filter it?

**Comment by sr320** [comment]
We are using a modified version of the 210601512 file. Specifically only
using scaffolds that are at least 10k bp in length.
Available @
http://owl.fish.washington.edu/halfshell/2016-11-oly-annotation/Ostrea_lurida-Scaff-10k.fa
