### ISSUE TITLE
Genome assembly

### ISSUE THREAD

**Issue by ksil91** [RobertsLab/project-olympia.oyster-genomic#27]
Here's [a paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5100563/) that tested a few assemblers for hybrid analysis and chose platanus.

Here's a [Biostars forum post](https://www.biostars.org/p/63047/) where someone used a combination of platanus and redundans with good success.

Don't know how to tag Sean in this wiki.

**Comment by sr320** [comment]
Surprisingly Sean ran into an issue with PacBio and Platanus..

https://github.com/sr320/LabDocs/issues/614

He offers some options

**Comment by seanb80** [comment]
Ah! I neglected to look in here first before posting my issue. Oops!

It looks like Redundans may be an option 4 along the same likes as the DBG2OLC route. I will look in to it.

**Comment by ksil91** [comment]
@seanb80 I just found out a committee member's lab uses a combination of Redundans/platanus on a mixed dataset of PacBio and Illumina mate pair on butterfly genomes. If you'd like, I can either get you in touch with their lab manager directly (she's nice) or get a copy of the parameters/pipeline they use.

**Comment by seanb80** [comment]
If it isn't too much trouble, sure! I've got a good idea of what should be down, but a second se of ideas so never bad. Thanks.

**Comment by sr320** [comment]
Here are some initial comparisons
https://github.com/sr320/nb-2017/blob/master/O_lurida/10-Comparing-Genome-Assemblies.ipynb
