### ISSUE TITLE
Assembly naming

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-olympia.oyster-genomic#32]
Is this a typo? Presumably these have different IDs?

![pic](http://eagle.fish.washington.edu/cnidarian/skitch/Genome_Assemblies_·_RobertsLab_project-olympia_oyster-genomic_Wiki_1FACD094.png)

**Comment by kubu4** [comment]
Yes, typo. Can fix this evening.

**Comment by kubu4** [comment]
Fixed.
