### ISSUE TITLE
RNA-Seq Data Available!

### ISSUE THREAD

**Issue by ksil91** [RobertsLab/project-olympia.oyster-genomic#33]
The RNASeq sequencing data from the adult oly OA experiment is in! This is not the QuantSeq(aka Tag-Seq) data yet, but the full mRNA sequencing for assembling a transcriptome to map the QuantSeq reads to. 
I have abductor, ctenidia, and mantle from a single California individual from both pH treatments (sampled 36 hours after pH was lowered) and then ctenidia from one individual from each of British Columbia and Oregon at both treatments. I also have a single pooled library of the gonad samples you sent me, containing 4 individuals encompassing both populations and both treatments.

I don't have an ideal data hosting option like you guys, but I'd like to make the data available and write a note about it on the olympia.oyster-genomic wiki along with the link to the [wet lab notebook](https://benchling.com/s/etr-5HBBfmBYAvQbzdrHjc61) I think I only have write privileges for my folder on Owl, so I can upload it there or give you the ftp info to download it direct to nightingale if that's what you'd prefer.

**Comment by kubu4** [comment]
ftp link would be great.
