### ISSUE TITLE
2bRAD resequencing data?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/project-olympia.oyster-genomic#36]
Is there data from the [2bRAD resequencing](https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/2bRAD-Resequencing-January-2017)?

**Comment by ksil91** [comment]
It was stored on my wetgenes folder. I updated the Wiki page. Let me know if you need more information or if I linked the files incorrectly.

**Comment by kubu4** [comment]
Thanks!
