### ISSUE TITLE
Identify any additional data regarding MBD-BSseq samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-olympia.oyster-genomic#4]
Need to gain as much info on the 18 samples subjected to MBD-BSseq and add to wiki page:
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/MBD-BSseq

Information to possibly include is size, is there any genetic data?, do we know anything about offspring?
...

```
E1_hc1_2B
E1_hc1_4B
E1_hc2_15B
E1_hc2_17
E1_hc3_1
E1_hc3_5
E1_hc3_7
E1_hc3_10
E1_hc3_11
E1_ss2_9B
E1_ss2_14B
E1_ss2_18B
E1_ss3_3B
E1_ss3_14B
E1_ss3_15B
E1_ss3_16B
E1_ss3_20
E1_ss5_18
```

Full story to date [here](http://onsnetwork.org/kubu4/category/olympia-oyster-reciprocal-transplant/mbd-enrichment-for-sequencing-at-zymoresearch/)

**Comment by kubu4** [comment]
Previous GitHub issue discussing these samples: https://github.com/sr320/LabDocs/issues/177

Took this from that discussion:

@ksil91 - can you remind me what tissue you extracted to obtain this DNA?

**Comment by sr320** [comment]
Now I am totally confused :) why are there links to 50+ files when 18 libraries were made?

**Comment by sr320** [comment]
Ok found explanation 
http://onsnetwork.org/kubu4/category/olympia-oyster-reciprocal-transplant/mbd-enrichment-for-sequencing-at-zymoresearch/

and willl incorporate into wiki

Still very interested to know if matching Rad data is available

**Comment by ksil91** [comment]
Adductor muscle tissue

**Comment by sr320** [comment]
@ksil91 

How about size, is there any genetic data (hope the answer is yes)?, do we know anything about offspring?

**Comment by ksil91** [comment]
I have wet weight and took pictures of them with a ruler- I can get the shell length in imageJ tomorrow. Should I make a separate wiki entry with that data?

These samples were all 2brad sequenced, and I will check to see how many reads they have after filtering to get an idea if they worked or not.

**Comment by sr320** [comment]
Thanks! New wiki or same would be just fine.

**Comment by ksil91** [comment]
Added wet weight for all samples to my [master sample sheet](https://docs.google.com/spreadsheets/d/1qrKW9QdtMMrSDHVRHzigEixuh7S8l10ZDySN5R5ZkPM/edit?usp=sharing)  (the same one that lists which samples I gave to you) and added some info to the wiki. Will get the rest of the lengths soon and put them up there.

As for offspring - do you mean do we know if they reproduced or not? I think we can get that by 2brad sequencing the one-day-old larvae samples. I'm a little swamped this quarter but I hope to get to those soon to send off for sequencing. If we are particularly interested in these samples I can prioritize sequencing larvae from families HC1, HC2, HC3, SS2, SS3, and SS5.

**Comment by jldimond** [comment]
Hi guys...I am starting to look into this a bit. First I want to make sure I understand the experiment. My understanding is that the samples are adult oysters, raised in a common garden, whose parents came from two different locations. 

If this is is correct, then say the methylomes turn out to be very similar - couldn't this be either because (a) they were similar to begin with and did not change, or (b) because they did change and became similar due to life in a similar environment? I just want to get a handle on this to understand what kinds of questions can be asked here.

**Comment by sr320** [comment]
You are correct.
