### ISSUE TITLE
Considerations for wiki organization

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-olympia.oyster-genomic#5]
As this is test run for project management, lets use this thread to discuss thoughts on organization

**Comment by sr320** [comment]
Random thoughts
1. Should this be organized based on sequence job or scientific question (or both) - leaning toward both.
2. What happens when we get multiple "MBD-Seq" etc when a tile of page is generic?

**Comment by kubu4** [comment]
Excellent points. Naming page based on scientific question seems the best approach.

Then, we'd have subheadings on the wiki sidebar for each question. Multiple sequencing runs/events for a particular scientific question should then be manageable and remain relatively organized.

I'll play around with stuff a bit.

**Comment by sr320** [comment]
done
