### ISSUE TITLE
Lotterhos sample clarification

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/project-olympia.oyster-genomic#7]
Saw that @sr320 struck out the following two samples from the sample list:
- NF2_6
- NF_18

Mostly to satisfy my own curiosity (and, I would like to correct the readme file on Owl for these two samples), but these are Olympia oyster samples provided by Katherine Silliman. How do they tie in to a Lotterhos project?

**Comment by sr320** [comment]
Did you check the spreadsheet? :smile:

**Comment by kubu4** [comment]
Which spreadsheet???

Reference to NGS spreadsheet?

**Comment by sr320** [comment]
These samples are done for us to compare to new method. No other direct use. Will create page for these "extra samples" soon.
